### ISSUE TITLE
Request for Update and Method Documentation

### ISSUE THREAD

**Issue by SDsly** [NousResearch/DisTrO#3]
Hi, I've been eagerly awaiting the DisTro updates mentioned a few months ago. It's been around three months since the last update, and I was wondering if you could provide an update on the current status of the project and an estimated timeline for the next release.

Additionally, I noticed that the latest release's report includes detailed results but lacks documentation on the methods used. This makes it challenging for users like myself to understand and implement your method. If possible, could you please provide more detailed documentation?

Thank you very much for your hard work and dedication to this project. 

Best regards

**Comment by adonishong** [comment]
+1 strongly looking forward to

**Comment by new-TonyWang** [comment]
+1 Also expecting to  this work

**Comment by arilotter** [comment]
DeMo, the foundational work for DisTrO, is now available with a paper & codebase. See the README.md file for more info!
